[tool.black]
line-length = 88
target-version = ['py39']  
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.venv
    | venv
    | __pycache__
    | migrations
    | db\.sqlite3
    | staticfiles
    | cypress
    | reports
)/
'''

