# Generated by Django 4.2.17 on 2024-12-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
