name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the 'main' branch

jobs:
  tests:
    runs-on: ubuntu-24.04  # Updated to ubuntu-24.04 for future compatibility

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust Python version if required

      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black

      # Step 6: Run unit tests
      - name: Run unit tests
        run: python manage.py test todo.tests

      # Step 7: Run integration tests
      - name: Run integration tests
        run: python manage.py test todo.tests_integration

      # Step 8: Upload test coverage report (optional)
      - name: Upload coverage report
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: coverage-report
          path: .coverage  # Adjust if coverage report is elsewhere

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies (including Cypress)
      - name: Install dependencies
        run: npm install --save-dev cypress
        working-directory: ./todo/cypress

      # Step 4: Grant execute permissions for Cypress
      - name: Grant execute permissions for Cypress
        run: chmod +x ./todo/cypress/node_modules/cypress
        working-directory: ./todo/cypress

      # Step 5: Run Cypress tests
      - name: Run Cypress tests
        run: ./todo/cypress/node_modules/cypress run
        working-directory: ./todo/cypress

      # Optional Step 6: Upload Cypress test results
      - name: Upload Cypress test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: ./todo/cypress/cypress/results/
