name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the 'main' branch

jobs:
  tests:
    runs-on: ubuntu-24.04  # Updated to ubuntu-24.04 for future compatibility

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust Python version if required

      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black


      # Step 6: Run unit tests
      - name: Run unit tests
        run: python manage.py test todo.tests

      # Step 7: Run integration tests
      - name: Run integration tests
        run: python manage.py test todo.tests_integration

      # Step 8: Upload test coverage report (optional)
      - name: Upload coverage report
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: coverage-report
          path: .coverage  # Adjust if coverage report is elsewhere

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment (if needed for other parts of the project)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use your preferred Python version

      # Step 3: Set up Node.js environment for Cypress
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust to the Node.js version your project uses

      # Step 4: Install dependencies in the Cypress folder
      - name: Install dependencies (Cypress)
        run: |
          cd todo/cypress  # Navigate to the directory where package.json is located
          npm install  # Install the Node.js dependencies

      # Step 5: Ensure Cypress binary has the correct permissions
      - name: Ensure Cypress binary has execute permissions
        run: chmod +x $(npm bin)/cypress  # Add execute permissions for Cypress

      # Step 6: Run Cypress tests
      - name: Run Cypress tests
        run: |
          cd todo/cypress  # Ensure you're in the correct directory
          npx cypress run  # Run Cypress tests
