name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black

      - name: Run Flake8
        run: flake8 .

      - name: Run Black (Check Mode)
        run: black --check .

      - name: Run unit tests
        run: python manage.py test todo.tests

      - name: Run integration tests
        run: python manage.py test todo.tests_integration

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        run: python manage.py migrate

      - name: Start Django server
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
        continue-on-error: false

      - name: Install Selenium and WebDriver Manager
        run: |
          pip install selenium webdriver-manager

      - name: Run Selenium tests
        run: |
          python todo/tests_e2e.py
        continue-on-error: false

      - name: Stop Django server
        run: pkill -f runserver
        continue-on-error: true

      - name: Upload Selenium test results
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-results
          path: ./todo/selenium_tests/results/
