name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black

      # Step 6: Run unit tests
      - name: Run unit tests
        run: python manage.py test todo.tests

      # Step 7: Run integration tests
      - name: Run integration tests
        run: python manage.py test todo.tests_integration

      # Step 8: Upload test coverage report (optional)
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: .coverage

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Apply migrations
      - name: Apply migrations
        run: python manage.py migrate

      # Step 5: Start Django server
      - name: Start Django server
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
        continue-on-error: false

      # Step 6: Set up Selenium dependencies
      - name: Install Selenium and WebDriver Manager
        run: |
          pip install selenium webdriver-manager

      # Step 7: Run Selenium tests
      - name: Run Selenium tests
        run: |
          python todo/tests_e2e.py
        continue-on-error: false

      # Step 8: Upload Selenium test results
      - name: Upload Selenium test results
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-results
          path: ./todo/selenium_tests/results/

